apiVersion: crossplane.dsoderlund.consulting/v1
kind: FullstackApp
metadata:
  name: __ignored__
spec:
  frontend:
    image: docker.io/dsoderlund/davidtest4-frontend:3f48ba2e
    replicas: 1
    containerPort: 80

