apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - davidtest-fullstackapp.yaml
patches:
  - path: davidtest-frontend.yaml
    target:
      kind: FullstackApp
  - path: davidtest-backend.yaml
    target:
      kind: FullstackApp