apiVersion: crossplane.dsoderlund.consulting/v1
kind: FullstackApp
metadata:
  name: __ignored__
spec:
  backend:
    image: docker.io/dsoderlund/sept10-backend:bc6a506e
    replicas: 1
    containerPort: 8080
    databaseConnectionValues: true
    extraEnvironmentVariables:
      - name: ASPNETCORE_ENVIRONMENT
        value: Production

