apiVersion: crossplane.dsoderlund.consulting/v1
kind: App
metadata:
  name: testapp
spec:
  containerPort: 80
  image: nginx:latest
  ingress:
    hostname: testapp.sam.dsoderlund.consulting
  replicas: 3
