apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aname-fullstackapp.yaml
patches:
  - path: aname-frontend.yaml
    target:
      kind: FullstackApp
  - path: aname-backend.yaml
    target:
      kind: FullstackApp