apiVersion: crossplane.dsoderlund.consulting/v1
kind: FullstackApp
metadata:
  name: "daviddemo-june9"
spec:
  backend:
    image: "docker.io/dsoderlund/daviddemo-june9-backend:latest"
    replicas: 1
    containerPort: 8080
    databaseConnectionValues: true
    extraEnvironmentVariables:
      - name: ASPNETCORE_ENVIRONMENT
        value: "Production"
  frontend:
    image: "docker.io/dsoderlund/daviddemo-june9-frontend:latest"
    replicas: 1
    containerPort: 80
  ingress:
    hostname: "daviddemo-june9.sam.dsoderlund.consulting"
  database:
    replicas: 1