kind: FullstackApp
apiVersion: crossplane.dsoderlund.consulting/v1
metadata:
  name: daviddemo-june9
spec:
  backend:
    replicas: 1
    databaseConnectionValues: true
    image: docker.io/dsoderlund/daviddemo-june9-backend:TJÄÄNA
    containerPort: 8080
    extraEnvironmentVariables:
    - value: Production
      name: ASPNETCORE_ENVIRONMENT
  database:
    replicas: 1
  ingress:
    hostname: daviddemo-june9.sam.dsoderlund.consulting
  frontend:
    image: docker.io/dsoderlund/daviddemo-june9-frontend:fronty2
    containerPort: 80
    replicas: 1

