spec:
  frontend:
    image: docker.io/dsoderlund/developersbay-frontend:4d7ec38c
    containerPort: 80
    replicas: 1
  ingress:
    hostname: developersbay.sam.dsoderlund.consulting
  database:
    replicas: 1
  backend:
    containerPort: 8080
    image: docker.io/dsoderlund/developersbay-backend:0.0.1
    replicas: 1
    extraEnvironmentVariables:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    databaseConnectionValues: true
metadata:
  name: developersbay
kind: FullstackApp
apiVersion: crossplane.dsoderlund.consulting/v1

