apiVersion: crossplane.dsoderlund.consulting/v1
kind: FullstackApp
metadata:
  name: developersbay
spec:
  ingress:
    hostname: developersbay.sam.dsoderlund.consulting
  backend:
    databaseConnectionValues: true
    image: docker.io/dsoderlund/developersbay-backend:321
    extraEnvironmentVariables:
    - value: Production
      name: ASPNETCORE_ENVIRONMENT
    replicas: 1
    containerPort: 8080
  database:
    replicas: 1
  frontend:
    image: docker.io/dsoderlund/developersbay-frontend:2f56b874
    containerPort: 80
    replicas: 1

