apiVersion: crossplane.dsoderlund.consulting/v1
kind: FullstackApp
metadata:
  name: developersbay
spec:
  backend:
    image: docker.io/dsoderlund/developersbay-frontend:y
    replicas: 1
    containerPort: 8080
    databaseConnectionValues: true
    extraEnvironmentVariables:
      - name: ASPNETCORE_ENVIRONMENT
        value: Production
  frontend:
    image: docker.io/dsoderlund/developersbay-frontend:123
    replicas: 1
    containerPort: 80
  ingress:
    hostname: developersbay.sam.dsoderlund.consulting
  database:
    replicas: 1

