apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - test-kustomize-fullstackapp.yaml
patches:
  - path: test-kustomize-frontend.yaml
    target:
      kind: FullstackApp
  - path: test-kustomize-backend.yaml
    target:
      kind: FullstackApp