apiVersion: crossplane.dsoderlund.consulting/v1
kind: FullstackApp
metadata:
  name: __ignored__
spec:
  frontend:
    image: docker.io/dsoderlund/en-sista-demo-frontend:d9e85bdd
    replicas: 1
    containerPort: 80

