name: Update demo-gitops Application images
on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to update'
        required: true
        type: string
      subComponent:
        description: 'Sub-component to update'
        required: false
        type: string
        default: ""
      newTag:
        description: 'Tag to set'
        required: true
        type: string
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Finds component recursively in appset and sets new tag
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml
          Import-Module powershell-yaml

          $newTag = "${{ inputs.newTag }}"
          $component = "${{ inputs.component }}"
          $subComponent = "${{ inputs.subComponent }}"

          Write-Host "Updating $component to $newTag for subcomponent $subComponent"
          

          $ComponentPath = Get-ChildItem gitops/apps/github-appset/ -Recurse -Filter $component -Directory | Select-Object -ExpandProperty FullName
          $ComponentPath | Get-ChildItem -Filter *.yaml | ForEach-Object {
              $document = Get-Content $_ | ConvertFrom-Yaml
              # it recursively finds "image" within spec, and if it is found under a node, checks if that node matches $subComponent unless $subComponent is ignored.
              $document.spec.GetEnumerator() | Where-Object {
                  $_.Value -is [System.Collections.IDictionary] -and ($_.Name -eq $subComponent -or $subComponent -eq '' -or $null -eq $subComponent)
              } | ForEach-Object {
                  $_.Value.image = $_.Value.image -replace '(?m):.*$', ":$newTag"
              }
              $document | ConvertTo-Yaml | Set-Content $_
          }
      - uses: EndBug/add-and-commit@v9
        with:
          add: gitops/apps/github-appset/
          default_author: github_actor
          push: true